# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_csv_file = "../output_data/city.csv"

weather_df = pd.read_csv(weather_csv_file)

weather_df.head()

,City ID,City,Country,Lat,Lng,Temperature,Humidity,Clouds,Wind Speed
0,6167865,Toronto,CA,43.7001,-79.4163,28.94,47,32,7.96
1,3833367,Ushuaia,AR,-54.8000,-68.3000,44.60,57,40,35.68
2,4020109,Atuona,PF,-9.8000,-139.0333,78.76,62,72,2.73
3,3883457,Lebu,CL,-37.6167,-73.6500,64.87,61,0,8.61
4,6165406,Thompson,CA,55.7435,-97.8558,15.80,67,20,11.50

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
# Configure gmaps with API key.
gmaps.configure(api_key=g_key)

# Convert Humidity to float and store
# Also, handle NaN values
weather_df = weather_df.dropna()
humidity = weather_df["Humidity"].astype(float)

# Store 'Latitude' and 'Longitude' into  locations. 
locations = weather_df[["Lat", "Lng"]].astype(float)

# Create a humidity Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=max(weather_df["Humidity"]),
                                 point_radius = 2)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
# Narrow down the DataFrame to find your ideal weather condition.
filtered_weather_df = weather_df

# Drop any rows that don't contain all three conditions. Want to be sure the weather is ideal.

# A max temperature lower than 80 degrees but higher than 70.
filtered_weather_df = filtered_weather_df.loc[(filtered_weather_df["Temperature"] < 80) & (filtered_weather_df["Temperature"] > 70)]

# Wind speed less than 10 mph.
filtered_weather_df = filtered_weather_df.loc[filtered_weather_df["Wind Speed"] < 10]

# Zero cloudiness.
filtered_weather_df = filtered_weather_df.loc[filtered_weather_df["Clouds"] == 0]

# Drop any rows with null values
filtered_weather_df = filtered_weather_df.dropna()

filtered_weather_df

,City ID,City,Country,Lat,Lng,Temperature,Humidity,Clouds,Wind Speed
6,110690,Faya,SA,18.3851,42.4509,71.60,49,0,9.22
16,3430863,Mar del Plata,AR,-38.0023,-57.5575,73.40,49,0,9.22
36,2171722,Charters Towers,AU,-20.1000,146.2667,72.32,83,0,6.51
82,3892454,Diego de Almagro,CL,-26.3667,-70.0500,76.53,34,0,8.68
110,2139521,Noumea,NC,-22.2763,166.4572,73.40,78,0,9.35
405,4003739,Juchipila,MX,21.4167,-103.1167,72.09,24,0,1.74
456,3462103,Grão Mogol,BR,-16.5594,-42.8897,79.97,53,0,6.40
509,7647007,Bariloche,AR,-41.1456,-71.3082,70.77,36,0,2.30
516,3879123,Nacimiento,CL,-37.5000,-72.6667,71.60,53,0,5.75
535,3881102,Machalí,CL,-34.1833,-70.6667,73.40,40,0,2.30

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
hotel_df = filtered_weather_df

# params dictionary to update each iteration
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}


for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {row['City']}.")
    response = requests.get(base_url, params=params).json()
    # print(json.dumps(response, indent=4, sort_keys=True))
    
    # extract results
    results = response['results']
    
    try:
        print(f"Closest hotel is {results[0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Retrieving Results for Index 6: Faya.
Closest hotel is مقبرة ال مجمل.
------------
Retrieving Results for Index 16: Mar del Plata.
Closest hotel is Gran Hotel Mar del Plata.
------------
Retrieving Results for Index 36: Charters Towers.
Closest hotel is Cattleman's Rest Motor Inn.
------------
Retrieving Results for Index 82: Diego de Almagro.
Closest hotel is hotel luna del desierto.
------------
Retrieving Results for Index 110: Noumea.
Closest hotel is Hôtel Le Lagon.
------------
Retrieving Results for Index 405: Juchipila.
Closest hotel is HOTEL JARDIN.
------------
Retrieving Results for Index 456: Grão Mogol.
Closest hotel is Pousada do Eti.
------------
Retrieving Results for Index 509: Bariloche.
Closest hotel is Hotel Patagonia.
------------
Retrieving Results for Index 516: Nacimiento.
Closest hotel is Residencial San Marcos.
------------
Retrieving Results for Index 535: Machalí.
Closest hotel is Mining House.
------------

In [7]:
hotel_df

,City ID,City,Country,Lat,Lng,Temperature,Humidity,Clouds,Wind Speed,Hotel Name
6,110690,Faya,SA,18.3851,42.4509,71.60,49,0,9.22,مقبرة ال مجمل
16,3430863,Mar del Plata,AR,-38.0023,-57.5575,73.40,49,0,9.22,Gran Hotel Mar del Plata
36,2171722,Charters Towers,AU,-20.1000,146.2667,72.32,83,0,6.51,Cattleman's Rest Motor Inn
82,3892454,Diego de Almagro,CL,-26.3667,-70.0500,76.53,34,0,8.68,hotel luna del desierto
110,2139521,Noumea,NC,-22.2763,166.4572,73.40,78,0,9.35,Hôtel Le Lagon
405,4003739,Juchipila,MX,21.4167,-103.1167,72.09,24,0,1.74,HOTEL JARDIN
456,3462103,Grão Mogol,BR,-16.5594,-42.8897,79.97,53,0,6.40,Pousada do Eti
509,7647007,Bariloche,AR,-41.1456,-71.3082,70.77,36,0,2.30,Hotel Patagonia
516,3879123,Nacimiento,CL,-37.5000,-72.6667,71.60,53,0,5.75,Residencial San Marcos
535,3881102,Machalí,CL,-34.1833,-70.6667,73.40,40,0,2.30,Mining House

In [8]:
# NOTE: Do not change any of the code in this cell
# Assign the marker layer to a variable
locations = hotel_df[["Lat", "Lng"]]
markers = gmaps.marker_layer(locations)


# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [9]:
# Create hotel symbol layer
hotel_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=2,
    info_box_content=hotel_info)
# Add marker layer ontop of heat map
fig.add_layer(markers)
fig.add_layer(hotel_layer)
fig

# Display figure

Figure(layout=FigureLayout(height='420px'))